package simpledb;

import java.util.*;

/**
 * The Join operator implements the relational join operation.
 */
public class Join extends Operator {

    private static final long serialVersionUID = 1L;

    private JoinPredicate predicate;
    private DbIterator child1, child2;
    private Tuple tuple1, tuple2;
    private TupleDesc tupleDesc;
    private boolean isEqPredicate;
    private HashEquiJoin hashEquiJoin;

    /**
     * Constructor. Accepts to children to join and the predicate to join them
     * on
     * 
     * @param p
     *            The predicate to use to join the children
     * @param child1
     *            Iterator for the left(outer) relation to join
     * @param child2
     *            Iterator for the right(inner) relation to join
     */
    public Join(JoinPredicate p, DbIterator child1, DbIterator child2) {
        this.predicate = p;
        this.child1 = child1;
        this.child2 = child2;
        this.tuple1 = null;
        this.tuple2 = null;
        this.tupleDesc = TupleDesc.merge(child1.getTupleDesc(), child2.getTupleDesc());
        this.isEqPredicate = p.getOperator().equals(Predicate.Op.EQUALS);
        this.hashEquiJoin = (isEqPredicate ? new HashEquiJoin(p, child1, child2) : null);
    }

    public JoinPredicate getJoinPredicate() {
        return predicate;
    }

    /**
     * @return
     *       the field name of join field1. Should be quantified by
     *       alias or table name.
     * */
    public String getJoinField1Name() {
        return child1.getTupleDesc().getFieldName(predicate.getField1());
    }

    /**
     * @return
     *       the field name of join field2. Should be quantified by
     *       alias or table name.
     * */
    public String getJoinField2Name() {
        return child2.getTupleDesc().getFieldName(predicate.getField2());
    }

    /**
     * @see simpledb.TupleDesc#merge(TupleDesc, TupleDesc) for possible
     *      implementation logic.
     */
    public TupleDesc getTupleDesc() {
        return tupleDesc;
    }

    public void open() throws DbException, NoSuchElementException,
            TransactionAbortedException {
        if (isEqPredicate) {
            hashEquiJoin.open();
        }
        else {
            child1.open();
            child2.open();
        }
        super.open();
    }

    public void close() {
        if (isEqPredicate) {
            hashEquiJoin.close();
        }
        else {
            child1.close();
            child2.close();
        }
        super.close();
    }

    public void rewind() throws DbException, TransactionAbortedException {
        child1.rewind();
        child2.rewind();
    }

    /**
     * Returns the next tuple generated by the join, or null if there are no
     * more tuples. Logically, this is the next tuple in r1 cross r2 that
     * satisfies the join predicate. There are many possible implementations;
     * the simplest is a nested loops join.
     * <p>
     * Note that the tuples returned from this particular implementation of Join
     * are simply the concatenation of joining tuples from the left and right
     * relation. Therefore, if an equality predicate is used there will be two
     * copies of the join attribute in the results. (Removing such duplicate
     * columns can be done with an additional projection operator if needed.)
     * <p>
     * For example, if one tuple is {1,2,3} and the other tuple is {1,5,6},
     * joined on equality of the first column, then this returns {1,2,3,1,5,6}.
     * 
     * @return The next matching tuple.
     * @see JoinPredicate#filter
     */
    protected Tuple fetchNext() throws TransactionAbortedException, DbException {
        if (isEqPredicate) {
            return hashEquiJoin.fetchNext();
        }
        if (tuple1 == null) {
            if (child1.hasNext()) {
                tuple1 = child1.next();
            }
            else {
                return null;
            }
        }
        tuple2 = null;
        while (tuple1 != null) {
            while (child2.hasNext()) {
                tuple2 = child2.next();
                if (predicate.filter(tuple1, tuple2)) {
                    Tuple tuple = new Tuple(TupleDesc.merge(tuple1.getTupleDesc(), tuple2.getTupleDesc()));
                    setJoinResult(tuple, tuple1, tuple2);
                    return tuple;
                }
            }
            if (child1.hasNext()) {
                tuple1 = child1.next();
                child2.rewind();
            }
            else {
                return null;
            }
        }
        return null;
    }

    @Override
    public DbIterator[] getChildren() {
        return new DbIterator[] {child1, child2};
    }

    @Override
    public void setChildren(DbIterator[] children) {
        if (isEqPredicate) {
            hashEquiJoin.setChildren(children);
        }
        child1 = children[0];
        child2 = children[1];
    }

    static void setJoinResult(Tuple dest, Tuple tuple1, Tuple tuple2) {
        int fieldNum1 = tuple1.getTupleDesc().numFields();
        int fieldNum2 = tuple2.getTupleDesc().numFields();
        for (int i = 0; i < fieldNum1; ++i) {
            dest.setField(i, tuple1.getField(i));
        }
        for (int i = 0; i < fieldNum2; ++i) {
            dest.setField(i + fieldNum1, tuple2.getField(i));
        }
    }

}
